// <auto-generated />
using System;
using CafeChain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CafeChain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CafeChain.Models.Customers.Customer", b =>
                {
                    b.Property<int>("CusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CusId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CusId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerAddress", b =>
                {
                    b.Property<int>("CusAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CusAId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<int?>("WarId")
                        .HasColumnType("int");

                    b.Property<int?>("WardWarId")
                        .HasColumnType("int");

                    b.HasKey("CusAId");

                    b.HasIndex("CusId");

                    b.HasIndex("WarId");

                    b.HasIndex("WardWarId");

                    b.ToTable("CustomerAddresses", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerBank", b =>
                {
                    b.Property<int>("CusBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CusBId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.HasKey("CusBId");

                    b.HasIndex("CusId");

                    b.HasIndex("BankName", "AccountNumber")
                        .IsUnique();

                    b.ToTable("CustomerBanks", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerPhone", b =>
                {
                    b.Property<int>("CusPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CusPId"));

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CusPId");

                    b.HasIndex("CusId", "Phone")
                        .IsUnique();

                    b.ToTable("CustomerPhones", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerPoint", b =>
                {
                    b.Property<int>("CusPoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CusPoId"));

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("CusPoId");

                    b.HasIndex("CusId")
                        .IsUnique();

                    b.ToTable("CustomerPoints", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Customers.Rating", b =>
                {
                    b.Property<int>("RatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CusId")
                        .HasColumnType("int");

                    b.Property<int?>("DriId")
                        .HasColumnType("int");

                    b.Property<int?>("DrinkDriId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.HasKey("RatId");

                    b.HasIndex("DriId");

                    b.HasIndex("DrinkDriId");

                    b.HasIndex("CusId", "DriId")
                        .IsUnique()
                        .HasFilter("[CusId] IS NOT NULL AND [DriId] IS NOT NULL");

                    b.ToTable("Ratings", null, t =>
                        {
                            t.HasCheckConstraint("CK_Rating_Stars", "[Stars] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Drink", b =>
                {
                    b.Property<int>("DriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("CatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DriId");

                    b.HasIndex("CatId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Drinks", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkCategory", b =>
                {
                    b.Property<int>("CatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CatId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CatId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DrinkCategories", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkImage", b =>
                {
                    b.Property<int>("DriIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriIId"));

                    b.Property<int>("DriId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DriIId");

                    b.HasIndex("DriId");

                    b.ToTable("DrinkImages", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkSize", b =>
                {
                    b.Property<int>("DriSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriSId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DriId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SizId")
                        .HasColumnType("int");

                    b.HasKey("DriSId");

                    b.HasIndex("SizId");

                    b.HasIndex("DriId", "SizId")
                        .IsUnique();

                    b.ToTable("DrinkSizes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkTopping", b =>
                {
                    b.Property<int>("DriTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriTId"));

                    b.Property<int>("DriId")
                        .HasColumnType("int");

                    b.Property<int>("TopId")
                        .HasColumnType("int");

                    b.HasKey("DriTId");

                    b.HasIndex("TopId");

                    b.HasIndex("DriId", "TopId")
                        .IsUnique();

                    b.ToTable("DrinkToppings", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Recipe", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecId"));

                    b.Property<int>("DriId")
                        .HasColumnType("int");

                    b.HasKey("RecId");

                    b.HasIndex("DriId")
                        .IsUnique();

                    b.ToTable("Recipes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.RecipeDetail", b =>
                {
                    b.Property<int>("RecDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecDId"));

                    b.Property<int>("IngId")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientIngId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("RecId")
                        .HasColumnType("int");

                    b.HasKey("RecDId");

                    b.HasIndex("IngId");

                    b.HasIndex("IngredientIngId");

                    b.HasIndex("RecId", "IngId")
                        .IsUnique();

                    b.ToTable("RecipeDetails", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Size", b =>
                {
                    b.Property<int>("SizId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SizId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sizes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Topping", b =>
                {
                    b.Property<int>("TopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TopId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Toppings", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.Ingredient", b =>
                {
                    b.Property<int>("IngId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IngId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.InventoryTransaction", b =>
                {
                    b.Property<int>("InvTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvTId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("InventoryTransactionTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int?>("RefId")
                        .HasColumnType("int");

                    b.Property<string>("RefType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StoIId")
                        .HasColumnType("int");

                    b.HasKey("InvTId");

                    b.HasIndex("InventoryTransactionTypeId");

                    b.HasIndex("StoIId");

                    b.ToTable("InventoryTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_InventoryTransaction_Qty", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.InventoryTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("InventoryTransactionTypes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.StockImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffStaId")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("StaffStaId");

                    b.HasIndex("StoreId");

                    b.ToTable("StockImports", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.StockImportDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("StockImportId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("StockImportId", "IngredientId")
                        .IsUnique();

                    b.ToTable("StockImportDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_StockImportDetail_Price", "[UnitPrice] >= 0");

                            t.HasCheckConstraint("CK_StockImportDetail_Qty", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Country", b =>
                {
                    b.Property<int>("CouId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CouId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Province", b =>
                {
                    b.Property<int>("ProId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProId"));

                    b.Property<int?>("CouId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ProId");

                    b.HasIndex("CouId", "Name")
                        .IsUnique()
                        .HasFilter("[CouId] IS NOT NULL");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Ward", b =>
                {
                    b.Property<int>("WarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ProId")
                        .HasColumnType("int");

                    b.HasKey("WarId");

                    b.HasIndex("ProId", "Name")
                        .IsUnique()
                        .HasFilter("[ProId] IS NOT NULL");

                    b.ToTable("Wards", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Loyalties.MemberLevel", b =>
                {
                    b.Property<int>("MemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemId"));

                    b.Property<int?>("MaxPoints")
                        .HasColumnType("int");

                    b.Property<int>("MinPoints")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MemberLevels", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Loyalties.PointTransaction", b =>
                {
                    b.Property<int>("PoiTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PoiTId"));

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerCusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrdId")
                        .HasColumnType("int");

                    b.Property<int>("PointTransactionTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.HasKey("PoiTId");

                    b.HasIndex("CusId");

                    b.HasIndex("CustomerCusId");

                    b.HasIndex("OrdId");

                    b.HasIndex("PointTransactionTypeId");

                    b.ToTable("PointTransactions", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Loyalties.PointTransactionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PointTransactionTypes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Orders.DiningTable", b =>
                {
                    b.Property<int>("TabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TabId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StoId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreStoId")
                        .HasColumnType("int");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("TabId");

                    b.HasIndex("StoreStoId");

                    b.HasIndex("StoId", "TableNumber")
                        .IsUnique();

                    b.ToTable("DiningTables", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Orders.KitchenOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("KitchenOrders", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Orders.Order", b =>
                {
                    b.Property<int>("OrdId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CusId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrSId")
                        .HasColumnType("int");

                    b.Property<int>("OrTId")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StaId")
                        .HasColumnType("int");

                    b.Property<int>("StoId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreStoId")
                        .HasColumnType("int");

                    b.Property<int?>("TabId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrdId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CusId");

                    b.HasIndex("OrSId");

                    b.HasIndex("OrTId");

                    b.HasIndex("StaId");

                    b.HasIndex("StoId");

                    b.HasIndex("StoreStoId");

                    b.HasIndex("TabId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderDetail", b =>
                {
                    b.Property<int>("OrDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrDId"));

                    b.Property<int>("DriId")
                        .HasColumnType("int");

                    b.Property<string>("DrinkName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SizId")
                        .HasColumnType("int");

                    b.Property<string>("SizeName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrDId");

                    b.HasIndex("DriId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SizId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderStatus", b =>
                {
                    b.Property<int>("OrSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrSId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrSId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OrderStatuses", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderTopping", b =>
                {
                    b.Property<int>("OrTgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrTgId"));

                    b.Property<int>("OrDId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TopId")
                        .HasColumnType("int");

                    b.Property<string>("ToppingName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ToppingTopId")
                        .HasColumnType("int");

                    b.HasKey("OrTgId");

                    b.HasIndex("TopId");

                    b.HasIndex("ToppingTopId");

                    b.HasIndex("OrDId", "TopId")
                        .IsUnique();

                    b.ToTable("OrderToppings", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderType", b =>
                {
                    b.Property<int>("OrTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrTId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("OrTId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OrderTypes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Payments.CashSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("EndCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OpenTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffStaId")
                        .HasColumnType("int");

                    b.Property<decimal?>("StartCash")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("StaffStaId");

                    b.HasIndex("StoreId");

                    b.ToTable("CashSessions", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Payments.Payment", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CashSessionId")
                        .HasColumnType("int");

                    b.Property<int>("OrdId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayMId")
                        .HasColumnType("int");

                    b.Property<int>("PaySId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PayId");

                    b.HasIndex("CashSessionId");

                    b.HasIndex("OrdId");

                    b.HasIndex("PayMId");

                    b.HasIndex("PaySId");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Payments.PaymentMethod", b =>
                {
                    b.Property<int>("PayMId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayMId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PayMId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentMethods", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Payments.PaymentStatus", b =>
                {
                    b.Property<int>("PaySId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaySId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaySId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("PaymentStatuses", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.ScopeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScopeTypes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Shift", b =>
                {
                    b.Property<int>("ShiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsOvernight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("StoId")
                        .HasColumnType("int");

                    b.HasKey("ShiId");

                    b.HasIndex("StoId");

                    b.ToTable("Shifts", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Staff", b =>
                {
                    b.Property<int>("StaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StoId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreStoId")
                        .HasColumnType("int");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("StoId");

                    b.HasIndex("StoreStoId");

                    b.ToTable("Staffs", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffBank", b =>
                {
                    b.Property<int>("StaBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaBId"));

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StaId")
                        .HasColumnType("int");

                    b.HasKey("StaBId");

                    b.HasIndex("StaId");

                    b.HasIndex("BankName", "AccountNumber")
                        .IsUnique()
                        .HasFilter("[AccountNumber] IS NOT NULL");

                    b.ToTable("StaffBanks", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffRole", b =>
                {
                    b.Property<int>("StaRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaRId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("StaId")
                        .HasColumnType("int");

                    b.HasKey("StaRId");

                    b.HasIndex("RoleId");

                    b.HasIndex("StaId", "RoleId")
                        .IsUnique();

                    b.ToTable("StaffRoles", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffScope", b =>
                {
                    b.Property<int>("StaSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaSId"));

                    b.Property<int>("ScopeRefId")
                        .HasColumnType("int");

                    b.Property<int>("ScopeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("StaId")
                        .HasColumnType("int");

                    b.HasKey("StaSId");

                    b.HasIndex("ScopeTypeId");

                    b.HasIndex("StaId");

                    b.HasIndex("StaId", "ScopeTypeId", "ScopeRefId")
                        .IsUnique();

                    b.ToTable("StaffScopes", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffShift", b =>
                {
                    b.Property<int>("StaSId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaSId"));

                    b.Property<int>("ShiId")
                        .HasColumnType("int");

                    b.Property<int>("StaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime2");

                    b.HasKey("StaSId");

                    b.HasIndex("ShiId");

                    b.HasIndex("WorkDate");

                    b.HasIndex("StaId", "ShiId", "WorkDate")
                        .IsUnique();

                    b.ToTable("StaffShifts", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Stores.Store", b =>
                {
                    b.Property<int>("StoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("WarId")
                        .HasColumnType("int");

                    b.Property<int?>("WardWarId")
                        .HasColumnType("int");

                    b.HasKey("StoId");

                    b.HasIndex("WarId");

                    b.HasIndex("WardWarId");

                    b.ToTable("Stores", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Stores.StoreDrink", b =>
                {
                    b.Property<int>("StoDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoDId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("DriId")
                        .HasColumnType("int");

                    b.Property<int>("StoId")
                        .HasColumnType("int");

                    b.HasKey("StoDId");

                    b.HasIndex("DriId");

                    b.HasIndex("StoId", "DriId")
                        .IsUnique();

                    b.ToTable("StoreDrinks", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Stores.StoreInventory", b =>
                {
                    b.Property<int>("StoIId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoIId"));

                    b.Property<decimal>("AvailableQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<int>("IngId")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientIngId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("ReservedQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0m);

                    b.Property<int>("StoId")
                        .HasColumnType("int");

                    b.HasKey("StoIId");

                    b.HasIndex("IngId");

                    b.HasIndex("IngredientIngId");

                    b.HasIndex("StoId", "IngId")
                        .IsUnique();

                    b.ToTable("StoreInventories", null, t =>
                        {
                            t.HasCheckConstraint("CK_StoreInventory_Qty", "[AvailableQty] >= 0 AND [ReservedQty] >= 0");
                        });
                });

            modelBuilder.Entity("CafeChain.Models.Stores.StoreTopping", b =>
                {
                    b.Property<int>("StoTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoTId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("StoId")
                        .HasColumnType("int");

                    b.Property<int>("TopId")
                        .HasColumnType("int");

                    b.HasKey("StoTId");

                    b.HasIndex("StoId");

                    b.HasIndex("TopId");

                    b.ToTable("StoreToppings", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Vouchers.OrderVoucher", b =>
                {
                    b.Property<int>("OrVId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrVId"));

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdId")
                        .HasColumnType("int");

                    b.Property<int>("VouId")
                        .HasColumnType("int");

                    b.HasKey("OrVId");

                    b.HasIndex("OrdId")
                        .IsUnique();

                    b.HasIndex("VouId");

                    b.ToTable("OrderVouchers", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Vouchers.Voucher", b =>
                {
                    b.Property<int>("VouId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VouId"));

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<int?>("MaxUsagePerUser")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinOrderValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VouId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vouchers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Voucher_Discount", "(DiscountPercent IS NOT NULL AND DiscountAmount IS NULL) OR (DiscountPercent IS NULL AND DiscountAmount IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CafeChain.Models.Vouchers.VoucherUsage", b =>
                {
                    b.Property<int>("VouUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VouUId"));

                    b.Property<int>("CusId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerCusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UsedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("VouId")
                        .HasColumnType("int");

                    b.HasKey("VouUId");

                    b.HasIndex("CusId");

                    b.HasIndex("CustomerCusId");

                    b.HasIndex("VouId", "CusId")
                        .IsUnique();

                    b.ToTable("VoucherUsages", (string)null);
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerAddress", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Locations.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeChain.Models.Locations.Ward", null)
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("WardWarId");

                    b.Navigation("Customer");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerBank", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany("CustomerBanks")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerPhone", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany("CustomerPhones")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CafeChain.Models.Customers.CustomerPoint", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany("CustomerPoints")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CafeChain.Models.Customers.Rating", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany("Ratings")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeChain.Models.Drinks.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DriId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CafeChain.Models.Drinks.Drink", null)
                        .WithMany("Ratings")
                        .HasForeignKey("DrinkDriId");

                    b.Navigation("Customer");

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Drink", b =>
                {
                    b.HasOne("CafeChain.Models.Drinks.DrinkCategory", "Category")
                        .WithMany("Drinks")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkImage", b =>
                {
                    b.HasOne("CafeChain.Models.Drinks.Drink", "Drink")
                        .WithMany("DrinkImages")
                        .HasForeignKey("DriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkSize", b =>
                {
                    b.HasOne("CafeChain.Models.Drinks.Drink", "Drink")
                        .WithMany("DrinkSizes")
                        .HasForeignKey("DriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Drinks.Size", "Size")
                        .WithMany("DrinkSizes")
                        .HasForeignKey("SizId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkTopping", b =>
                {
                    b.HasOne("CafeChain.Models.Drinks.Drink", "Drink")
                        .WithMany("DrinkToppings")
                        .HasForeignKey("DriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Drinks.Topping", "Topping")
                        .WithMany("DrinkToppings")
                        .HasForeignKey("TopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Recipe", b =>
                {
                    b.HasOne("CafeChain.Models.Drinks.Drink", "Drink")
                        .WithMany("Recipes")
                        .HasForeignKey("DriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.RecipeDetail", b =>
                {
                    b.HasOne("CafeChain.Models.Inventories.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Inventories.Ingredient", null)
                        .WithMany("RecipeDetails")
                        .HasForeignKey("IngredientIngId");

                    b.HasOne("CafeChain.Models.Drinks.Recipe", "Recipe")
                        .WithMany("RecipeDetails")
                        .HasForeignKey("RecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.InventoryTransaction", b =>
                {
                    b.HasOne("CafeChain.Models.Inventories.InventoryTransactionType", "TransactionType")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("InventoryTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Stores.StoreInventory", "StoreInventory")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("StoIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreInventory");

                    b.Navigation("TransactionType");
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.StockImport", b =>
                {
                    b.HasOne("CafeChain.Models.Staffs.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Staffs.Staff", null)
                        .WithMany("StockImports")
                        .HasForeignKey("StaffStaId");

                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.StockImportDetail", b =>
                {
                    b.HasOne("CafeChain.Models.Inventories.Ingredient", "Ingredient")
                        .WithMany("StockImportDetails")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Inventories.StockImport", "StockImport")
                        .WithMany("Details")
                        .HasForeignKey("StockImportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("StockImport");
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Province", b =>
                {
                    b.HasOne("CafeChain.Models.Locations.Country", "Country")
                        .WithMany("Provinces")
                        .HasForeignKey("CouId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Ward", b =>
                {
                    b.HasOne("CafeChain.Models.Locations.Province", "Province")
                        .WithMany("Wards")
                        .HasForeignKey("ProId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Province");
                });

            modelBuilder.Entity("CafeChain.Models.Loyalties.PointTransaction", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Customers.Customer", null)
                        .WithMany("PointTransactions")
                        .HasForeignKey("CustomerCusId");

                    b.HasOne("CafeChain.Models.Orders.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrdId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeChain.Models.Loyalties.PointTransactionType", "Type")
                        .WithMany("Transactions")
                        .HasForeignKey("PointTransactionTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.DiningTable", b =>
                {
                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Stores.Store", null)
                        .WithMany("DiningTables")
                        .HasForeignKey("StoreStoId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.KitchenOrder", b =>
                {
                    b.HasOne("CafeChain.Models.Orders.Order", "Order")
                        .WithMany("KitchenOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.Order", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeChain.Models.Orders.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Orders.OrderType", "OrderType")
                        .WithMany("Orders")
                        .HasForeignKey("OrTId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Staffs.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Stores.Store", null)
                        .WithMany("Orders")
                        .HasForeignKey("StoreStoId");

                    b.HasOne("CafeChain.Models.Orders.DiningTable", "DiningTable")
                        .WithMany("Orders")
                        .HasForeignKey("TabId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("DiningTable");

                    b.Navigation("OrderStatus");

                    b.Navigation("OrderType");

                    b.Navigation("Staff");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderDetail", b =>
                {
                    b.HasOne("CafeChain.Models.Drinks.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Orders.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Drinks.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Drink");

                    b.Navigation("Order");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderTopping", b =>
                {
                    b.HasOne("CafeChain.Models.Orders.OrderDetail", "OrderDetail")
                        .WithMany("OrderToppings")
                        .HasForeignKey("OrDId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Drinks.Topping", "Topping")
                        .WithMany()
                        .HasForeignKey("TopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Drinks.Topping", null)
                        .WithMany("OrderToppings")
                        .HasForeignKey("ToppingTopId");

                    b.Navigation("OrderDetail");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("CafeChain.Models.Payments.CashSession", b =>
                {
                    b.HasOne("CafeChain.Models.Staffs.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Staffs.Staff", null)
                        .WithMany("CashSessions")
                        .HasForeignKey("StaffStaId");

                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany("CashSessions")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Payments.Payment", b =>
                {
                    b.HasOne("CafeChain.Models.Payments.CashSession", "CashSession")
                        .WithMany("Payments")
                        .HasForeignKey("CashSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeChain.Models.Orders.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Payments.PaymentMethod", "PaymentMethod")
                        .WithMany("Payments")
                        .HasForeignKey("PayMId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Payments.PaymentStatus", "PaymentStatus")
                        .WithMany("Payments")
                        .HasForeignKey("PaySId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CashSession");

                    b.Navigation("Order");

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Shift", b =>
                {
                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Staff", b =>
                {
                    b.HasOne("CafeChain.Models.Staffs.Role", null)
                        .WithMany("Staffs")
                        .HasForeignKey("RoleId");

                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Stores.Store", null)
                        .WithMany("Staffs")
                        .HasForeignKey("StoreStoId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffBank", b =>
                {
                    b.HasOne("CafeChain.Models.Staffs.Staff", "Staff")
                        .WithMany("StaffBanks")
                        .HasForeignKey("StaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffRole", b =>
                {
                    b.HasOne("CafeChain.Models.Staffs.Role", "Role")
                        .WithMany("StaffRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Staffs.Staff", "Staff")
                        .WithMany("StaffRoles")
                        .HasForeignKey("StaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffScope", b =>
                {
                    b.HasOne("CafeChain.Models.Staffs.ScopeType", "ScopeType")
                        .WithMany()
                        .HasForeignKey("ScopeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Staffs.Staff", "Staff")
                        .WithMany("StaffScopes")
                        .HasForeignKey("StaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScopeType");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.StaffShift", b =>
                {
                    b.HasOne("CafeChain.Models.Staffs.Shift", "Shift")
                        .WithMany("StaffShifts")
                        .HasForeignKey("ShiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Staffs.Staff", "Staff")
                        .WithMany("StaffShifts")
                        .HasForeignKey("StaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("CafeChain.Models.Stores.Store", b =>
                {
                    b.HasOne("CafeChain.Models.Locations.Ward", "Ward")
                        .WithMany()
                        .HasForeignKey("WarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CafeChain.Models.Locations.Ward", null)
                        .WithMany("Stores")
                        .HasForeignKey("WardWarId");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("CafeChain.Models.Stores.StoreDrink", b =>
                {
                    b.HasOne("CafeChain.Models.Drinks.Drink", "Drink")
                        .WithMany()
                        .HasForeignKey("DriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany("StoreDrinks")
                        .HasForeignKey("StoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drink");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Stores.StoreInventory", b =>
                {
                    b.HasOne("CafeChain.Models.Inventories.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Inventories.Ingredient", null)
                        .WithMany("StoreInventories")
                        .HasForeignKey("IngredientIngId");

                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany("StoreInventories")
                        .HasForeignKey("StoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CafeChain.Models.Stores.StoreTopping", b =>
                {
                    b.HasOne("CafeChain.Models.Stores.Store", "Store")
                        .WithMany("StoreToppings")
                        .HasForeignKey("StoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Drinks.Topping", "Topping")
                        .WithMany("StoreToppings")
                        .HasForeignKey("TopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("Topping");
                });

            modelBuilder.Entity("CafeChain.Models.Vouchers.OrderVoucher", b =>
                {
                    b.HasOne("CafeChain.Models.Orders.Order", "Order")
                        .WithMany("OrderVouchers")
                        .HasForeignKey("OrdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Vouchers.Voucher", "Voucher")
                        .WithMany("OrderVouchers")
                        .HasForeignKey("VouId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("CafeChain.Models.Vouchers.VoucherUsage", b =>
                {
                    b.HasOne("CafeChain.Models.Customers.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CafeChain.Models.Customers.Customer", null)
                        .WithMany("VoucherUsages")
                        .HasForeignKey("CustomerCusId");

                    b.HasOne("CafeChain.Models.Vouchers.Voucher", "Voucher")
                        .WithMany("VoucherUsages")
                        .HasForeignKey("VouId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("CafeChain.Models.Customers.Customer", b =>
                {
                    b.Navigation("CustomerAddresses");

                    b.Navigation("CustomerBanks");

                    b.Navigation("CustomerPhones");

                    b.Navigation("CustomerPoints");

                    b.Navigation("Orders");

                    b.Navigation("PointTransactions");

                    b.Navigation("Ratings");

                    b.Navigation("VoucherUsages");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Drink", b =>
                {
                    b.Navigation("DrinkImages");

                    b.Navigation("DrinkSizes");

                    b.Navigation("DrinkToppings");

                    b.Navigation("Ratings");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.DrinkCategory", b =>
                {
                    b.Navigation("Drinks");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Recipe", b =>
                {
                    b.Navigation("RecipeDetails");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Size", b =>
                {
                    b.Navigation("DrinkSizes");
                });

            modelBuilder.Entity("CafeChain.Models.Drinks.Topping", b =>
                {
                    b.Navigation("DrinkToppings");

                    b.Navigation("OrderToppings");

                    b.Navigation("StoreToppings");
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.Ingredient", b =>
                {
                    b.Navigation("RecipeDetails");

                    b.Navigation("StockImportDetails");

                    b.Navigation("StoreInventories");
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.InventoryTransactionType", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("CafeChain.Models.Inventories.StockImport", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Country", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Province", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("CafeChain.Models.Locations.Ward", b =>
                {
                    b.Navigation("CustomerAddresses");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("CafeChain.Models.Loyalties.PointTransactionType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.DiningTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.Order", b =>
                {
                    b.Navigation("KitchenOrders");

                    b.Navigation("OrderDetails");

                    b.Navigation("OrderVouchers");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderDetail", b =>
                {
                    b.Navigation("OrderToppings");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CafeChain.Models.Orders.OrderType", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("CafeChain.Models.Payments.CashSession", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CafeChain.Models.Payments.PaymentMethod", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CafeChain.Models.Payments.PaymentStatus", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Role", b =>
                {
                    b.Navigation("StaffRoles");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Shift", b =>
                {
                    b.Navigation("StaffShifts");
                });

            modelBuilder.Entity("CafeChain.Models.Staffs.Staff", b =>
                {
                    b.Navigation("CashSessions");

                    b.Navigation("StaffBanks");

                    b.Navigation("StaffRoles");

                    b.Navigation("StaffScopes");

                    b.Navigation("StaffShifts");

                    b.Navigation("StockImports");
                });

            modelBuilder.Entity("CafeChain.Models.Stores.Store", b =>
                {
                    b.Navigation("CashSessions");

                    b.Navigation("DiningTables");

                    b.Navigation("Orders");

                    b.Navigation("Staffs");

                    b.Navigation("StoreDrinks");

                    b.Navigation("StoreInventories");

                    b.Navigation("StoreToppings");
                });

            modelBuilder.Entity("CafeChain.Models.Stores.StoreInventory", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("CafeChain.Models.Vouchers.Voucher", b =>
                {
                    b.Navigation("OrderVouchers");

                    b.Navigation("VoucherUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
